apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdb
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
        - name: redisdb
          image: redis:latest