name: Component_Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  frontend_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: frontend_test_message
        run: echo "Running frontend test..."
      - name: run frontend test
        run: go test
        working-directory: frontend
  backend_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: backend_test_message
        run: echo "Running backend test..."
      - name: backend test
        run: go test
        working-directory: backend
      
