name: Component_Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Application_Build:
    runs-on: ubuntu-24.04
    steps:
    -  uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: build_application_message
      run: echo "Building application..."
    -  name: build_frontend
       run: go build
       working-directory: frontend
    -  name: build_backend
       run: go build
       working-directory: frontend
#TESTING    
  frontend_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: frontend_test_message
        run: echo "Running frontend test..."
      - name: run frontend test
        run: go test
        working-directory: frontend
  backend_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: backend_test_message
        run: echo "Running backend test..."
      - name: backend test
        run: go test
        working-directory: backend
      
